name: base
channels:
  - conda-forge
  - anaconda
  - defaults

dependencies:
  - python=3.6
  - pip=19.1.1
  - pandas=0.24.1
  - matplotlib=3.0.3
  - seaborn=0.9.0
  - pandas-gbq=0.10.0
  - scikit-learn=0.19.1
  - ipykernel=4.8.2
  - ipython=5.8
  - setuptools=40.4.3
  - urllib3=1.23
  - blosc=1.14.3
  - psycopg2=2.7.5
  - glob2=0.5
  - pybase64=0.5.0
  - gcsfs=0.2.2
  - s3fs=0.1.6
  - boto3=1.8.2
  - google-cloud-bigquery=1.12.1
  - google-api-python-client=1.7.9
